
mongo:
  host: "localhost"
  # host: "docker.for.mac.host.internal"
  port: "3306"
  user: "root"
  password: "12345678"
  dbname: "bscChain"

redis:
  host: "127.0.0.1"
  port: "6390"


chain_id: 123123412


